src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column(type: 'datetime')]
    #[Assert\GreaterThan('today UTC+2', message:'La date de l\'évènement doit être dans futur !' )]
    private ?\DateTimeInterface $startTime = null;

    #[ORM\Column]
    #[Assert\GreaterThan(30, message:'La duration de l\'évènement doit durer au moins 30 minutes !' )]
    private ?int $duration = null;

    #[ORM\Column(type: 'datetime')]
    #[Assert\GreaterThan('today UTC+2', message:'La date limite d\'inscription doit être dans futur !')]
    #[Assert\LessThan(propertyPath:'startTime', message:'La date limite d\'inscription doit être inférieur à la date de l\'évènement !' )]
    private ?\DateTimeInterface $deadLine = null;

    #[ORM\Column]
    #[Assert\GreaterThan(1, message:'Le numbre des places doit être au moins 2 !')]
    private ?int $placeMax = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $info = null;

    #[ORM\ManyToOne(inversedBy: 'event')]
    private ?Place $place = null;

    #[ORM\ManyToOne(inversedBy: 'events')]
    #[ORM\JoinColumn(nullable: false)]
    private ?State $state = null;

    #[ORM\ManyToOne(inversedBy: 'events')]
    private ?Site $site = null;

    #[ORM\ManyToOne(inversedBy: 'events')]
    #[ORM\JoinColumn(nullable: false)]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    private ?User $promoter = null;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'events_registered')]
    private Collection $users_events;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $cancelReason = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $Image = null;

    #[ORM\OneToMany(mappedBy: 'event', targetEntity: Comment::class)]
    private Collection $comments;

    /**
     * @param Collection $users_events
     */
    public function __construct()
    {
        $this->users_events = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->startTime;
    }

    public function setStartTime(\DateTimeInterface $startTime): self
    {
        $this->startTime = $startTime;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getDeadLine(): ?\DateTimeInterface
    {
        return $this->deadLine;
    }

    public function setDeadLine(\DateTimeInterface $deadLine): self
    {
        $this->deadLine = $deadLine;

        return $this;
    }

    public function getPlaceMax(): ?int
    {
        return $this->placeMax;
    }

    public function setPlaceMax(int $placeMax): static
    {
        $this->placeMax = $placeMax;

        return $this;
    }

    public function getInfo(): ?string
    {
        return $this->info;
    }

    public function setInfo(?string $info): static
    {
        $this->info = $info;

        return $this;
    }

    public function getEvents(): ?Place
    {
        return $this->events;
    }

    public function setEvents(?Place $events): static
    {
        $this->events = $events;

        return $this;
    }

    public function getState(): ?State
    {
        return $this->state;
    }

    public function setState(?State $state): static
    {
        $this->state = $state;

        return $this;
    }

    public function getSite(): ?Site
    {
        return $this->site;
    }

    public function setSite(?Site $site): static
    {
        $this->site = $site;

        return $this;
    }

    public function getPlace(): ?Place
    {
        return $this->place;
    }

    public function setPlace(?Place $place): static
    {
        $this->place = $place;

        return $this;
    }

    public function getPromoter(): ?User
    {
        return $this->promoter;
    }

    public function setPromoter(?User $promoter): static
    {
        $this->promoter = $promoter;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsersEvents(): Collection
    {
        return $this->users_events;
    }

    public function addUsersEvent(User $usersEvent): static
    {
        if (!$this->users_events->contains($usersEvent)) {
            $this->users_events->add($usersEvent);
        }

        return $this;
    }

    public function removeUsersEvent(User $usersEvent): static
    {
        $this->users_events->removeElement($usersEvent);

        return $this;
    }

    public function getCancelReason(): ?string
    {
        return $this->cancelReason;
    }

    public function setCancelReason(?string $cancelReason): static
    {
        $this->cancelReason = $cancelReason;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): static
    {
        $this->Image = $Image;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setEvent($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getEvent() === $this) {
                $comment->setEvent(null);
            }
        }

        return $this;
    }
}

src/Controller/AccueilController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\AccueilFormType;
use App\Repository\EventRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AccueilController extends AbstractController
{
    #[Route('/user/accueil', name: 'app_accueil', methods: ['POST','GET'])]
    public function accueil(Request $request,EventRepository $eventRepository, Security $security): Response
    {
        if ($security->getUser()) {

            $event = new Event();
            $userID = $this->getUser()->getId();
            $eventForm = $this->createForm(AccueilFormType::class, $event);
            $eventForm->handleRequest($request);

            if ( $eventForm->isSubmitted() && $eventForm->isValid()) {
                if ( $eventForm->get('site')->getData() ){
                    $siteID = $eventForm->get('site')->getData()->getId();
                } else {
                    $siteID = 0;
                }

                $isPromoterChoice = $eventForm->get('promoter')->getData();
                $isRegisteredChoice = $eventForm->get('registered')->getData();
                $isNotRegisteredChoice = $eventForm->get('notRegistered')->getData();
                $isOldEventChoice = $eventForm->get('oldEvent')->getData();
                $keyWord = $eventForm->get('key')->getData();
                $startDateTime = $eventForm->get('startDateTime')->getData();
                $endDateTime = $eventForm->get('endDateTime')->getData();

                ($isPromoterChoice) ? ($promoterID = $userID) : ($promoterID = 0);
                ($isOldEventChoice) ? ($maximumStateValue = 6) : ($maximumStateValue = 5);
                if (is_null($keyWord)) {
                    $keyWord = '-no search-';
                }

                $events = $eventRepository->findFilteredEvents($siteID, $userID, $startDateTime, $endDateTime, $promoterID, $keyWord, $maximumStateValue);

            } else {
                $events = $eventRepository->findBasicEvents($userID);
                $isRegisteredChoice = null;
                $isNotRegisteredChoice = null;
            }
        } else {
            return $this->redirectToRoute('app_login');
        }

        return $this->render('accueil/accueil.html.twig', [
            'events' => $events,
            'accueilForm' => $eventForm,
            'user' => $this->getUser(),
            'stateX' => [
                0 => 'En création',
                1 => 'En cours',
                2 => 'Fermé',
                3 => 'Activité en cours',
                4 => 'Activité passée',
                5 => 'Archivé/Annulé'
            ],
            'isRegisteredChoice' => $isRegisteredChoice,
            'isNotRegisteredChoice' => $isNotRegisteredChoice
        ]);
    }

    #[Route('welcome', name: 'app_welcome', methods: ['POST','GET'])]
    public function welcome(Request $request,EventRepository $eventRepository, Security $security): Response
    {
        return $this->render('accueil/welcome.html.twig', [
            'toto' => 'toto'
        ]);
    }

}

templates/accueil/accueil.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <style>
        .rowTop{
            display: flex;
            justify-content: space-between;
        }
        .form{
            width: 1000px;
            height: 240px;
            background: white;
            border-radius: 20px;
            display: flex;
            overflow: hidden;
            font-weight: bold;
            transition: all 0.2s ease-in-out;;
            cursor: pointer;
            font-size: 15px;
            box-shadow: -5px -5px 20px #fff, 5px 5px 20px #babecc;
            padding-top: 10px;
        }
        .card1{
            padding: 10px;
            background: lightskyblue;
            color:white;
            border: none;
            border-radius: 20px;
            overflow: hidden;
            font-weight: bold;
            transition: all 0.2s ease-in-out;;
            cursor: pointer;
            font-size: 15px;
            box-shadow: -5px -5px 20px #fff, 5px 5px 20px #babecc;
            padding-top: 20px;
        }
        .card{
            width: 362px;
            height: 450px;
            margin-bottom: 20px;
            box-shadow: -5px -5px 20px #fff, 5px 5px 20px #babecc;
        }

        .card-img-top{
            width: 362px;
            height: 200px;
        }
        .card:hover{
            transform: scale(1.05);
        }

        .nomSortie {
            word-wrap: break-word;
            width: 120px;
        }
        .left{
            padding: 10px;
            width: 362px;
            height: 260px;
        }
        .right{
            width: 500px;
            height: 260px;
        }
        .my-form input {
            margin-left: 3px;
            box-shadow: inset 1px 1px 2px #babecc, inset -2px -2px 3px #fff;
            box-sizing: border-box;
            position: absolute;

        }
        .my-form ::placeholder {
            color: transparent;
        }
        .submitBtn:hover {
            box-shadow: -2px -2px 5px #fff, 2px 2px 5px #babecc;
            transform: translateY(-2px);
        }
        .submitBtn, .my-form input {
            background-color: #ebecf0;
            text-shadow: 1px 1px 0 #fff;
            border-radius: 7px;
            font-size: 15px;
            padding: 12px;
            border: 0;
            outline: 0;
        }
        .containerAllEventsCards{
            display: flex;
            flex-wrap: wrap;
            margin-top: 50px;
            justify-content: space-evenly;
        }
        .containerCardTop{
            width: 362px;

            margin-bottom: 20px;

        }
        .bloc2DivTop{
            display: flex;
        }
        .topPage{
            display: flex;
            flex-wrap: wrap;
            margin-top: 50px;
            justify-content: space-evenly;
        }

        .toto{
            height: 250px;
        }
        @media only screen and (max-width: 600px) {
            . * {
                font-size: small;
            }
            .form{
                width: 320px;
                height: 200px;
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-content: center;
                font-size: 10px;
            }
            .left{
                width: 320px;
                height: 80px;
            }
            .card1{
                padding: 2px;
                border-radius: 2px;
                font-size: 5px;
            }
            .submitBtn {
                padding: 2px;
                color: #ff6f61;
                font-weight: bold;
                transition: all 0.2s ease-in-out;;
                cursor: pointer;
                font-size: 10px;
                box-shadow: -5px -5px 20px #fff, 5px 5px 20px #babecc;
            }
            .bloc2DivTop{
                display: flex;
                flex-direction: column;
            }

        }
    </style>

    {% block message %}{{ parent() }}{% endblock %}
    {{ form_start(accueilForm, {'attr': {'class': 'my-form'}})}}


    <div class="topPage">
        <div class="bloc2DivTop">
            <div class="containerCard  containerCardTop">
                <div class="card toto">
                    <div class="left">
                        {{ form_row(accueilForm.site) }}<br>
                        <div class="nomSortie">
                            {{ form_row(accueilForm.key) }}</div><br>
                        {{ form_row(accueilForm.startDateTime) }}<br>
                        {{ form_row(accueilForm.endDateTime) }}
                    </div>
                </div>
            </div>

            <div class="containerCard containerCardTop">
                <div class="card toto">
                    <div class="right">
                        {{ form_row(accueilForm.promoter) }}
                        {{ form_row(accueilForm.registered) }}
                        {{ form_row(accueilForm.notRegistered) }}
                        {{ form_row(accueilForm.oldEvent) }}
                        <br>
                        <button class="submitBtn">Rechercher</button>
                    </div>
                </div>
            </div>
        </div>



        <div>
            <div class="card1 containerCardTop toto" style="max-width: 18rem;">
                <h4>Date du jour: {{ "now"|date('d/m/Y')}}</h4><br><br>
                <h4>Participant: {{ user.firstname }} {{ user.lastname }}</h4>
            </div>
        </div>
    </div>




    <script src="{{ asset('javascript/accueil.js') }}"></script>
    {{ form_end(accueilForm)}}


<div class="containerAllEventsCards">
    {% for event in events %}
        {% set isPresent = '' %}
        {% for User in event.getUsersEvents %}
            {% if User.email == user.email %}
                {% set isPresent = 'present'%}
            {% endif %}
        {% endfor %}

        {% set canDisplay = '' %}
        {% if event.state.reference > 0 and event.state.reference < 5  %}
            {% set canDisplay = 'yes'%}
        {% endif %}

        {% set canWithDraw = '' %}
        {% if (event.state.reference == 1 or event.state.reference == 2) and isPresent %}
            {% set canWithDraw = 'yes'%}
        {% endif %}

        {% set canRegister = '' %}
        {% if event.state.reference == 1 and isPresent == '' %}
            {% set canRegister = 'yes'%}
        {% endif %}

        {% set canModifie = '' %}
        {% if event.state.reference == 0 and event.promoter.id == user.id %}
            {% set canModifie = 'yes'%}
        {% endif %}

        {% set canCancel = '' %}
        {% if event.state.reference < 3  and event.promoter.id == user.id %}
            {% set canCancel = 'yes'%}
        {% endif %}

        {% set canPublished = '' %}
        {% if event.state.reference == 0  and event.promoter.id == user.id %}
            {% set canPublished = 'yes'%}
        {% endif %}

        {% if (isPresent == 'present' and isRegisteredChoice) or (isPresent == '' and isNotRegisteredChoice) or (isRegisteredChoice is empty and isNotRegisteredChoice is empty) %}

                <div class="card">
                    <img class="card-img-top" src="{{ asset('./'~app_images_event_directory ~ '/' ~ event.image) }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ event.name }}</h5>
                        <p class="card-text">Date: {{ event.startTime|date('d/m/Y') }}</p>

                        {% set st = event.state.reference %}
                        <p class="card-text">Etat: {{ stateX[st] }}</p>
                        <p class="card-text">inscrit/nb places: {{ event.getUsersEvents.count }}/{{ event.placeMax }}</p>
                        <div class="card-text">
                            {% if canDisplay == 'yes' %}
                                <a href="{{ path('event_event', {'id': event.id}) }}" title="Détail de cet évènement"><button class="btn btn-info btn-sm">Afficher</button></a>
                            {% endif %}
                            {% if canWithDraw == 'yes' %}
                                <a href="{{ path('event_user_unregistered', {'id': event.id}) }}" title="Se désister de cet évènement"><button class="btn btn-warning btn-sm">Se désister</button></a>
                            {% endif %}
                            {% if (canRegister == 'yes' and event.getUsersEvents.count < event.placeMax) %}
                                <a href="{{ path('event_user_registered', {'id': event.id}) }}" title="S'incrire à cet évènement"><button class="btn btn-primary btn-sm">S'inscrire</button></a>
                            {% endif %}
                            {% if canModifie == 'yes' %}
                                <a href="{{ path('event_editEvent', {'id': event.id}) }}" title="Modifier cet évènement"><button class="btn btn-success btn-sm">Modifier</button></a>
                            {% endif %}
                            {% if canCancel == 'yes' %}
                                <a href="{{ path('event_cancelEvent', {'id': event.id}) }}" title="Annuler cet évènement"><button class="btn btn-danger btn-sm">Annuler</button></a>
                            {% endif %}
                            {% if canPublished == 'yes' %}
                                <a href="{{ path('event_publishEvent', {'id': event.id}) }}" title="Publier cet évènement"><button class="btn btn-success btn-sm">Publier</button></a>
                            {% endif %}

                        </div>
                    </div>
                </div>


        {% endif %}
    {% else %}
        {#            <tr><td colspan="5">Aucune donnée dans la BDD.</td></tr>#}
    {% endfor %}
    </div>


    <a href="{{ path('event_createEvent') }}"><button class="submitBtn">Créer une sortie</button></a>
{% endblock %}

templates/accueil/welcome.html.twig
{% block stylesheets %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

{% endblock %}

    <style>
        .globalContainer{
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        .top{
            display: flex;
            flex-direction: column;
            justify-content: center;
            flex-wrap: wrap;
            align-items: center;
            margin-top: 50px;
            margin-bottom: 20px;
        }
        .card-deck{
            display: flex;
            justify-content: center;
            align-content: center;
            margin-top: 50px;
        }
        .btn{
            margin-top: 50px;
            box-shadow: -5px -5px 20px #fff, 5px 5px 20px #babecc;
        }
        .btn:hover{
            transform: scale(1.05);
        }
        .card{
            width: 362px;
            height: 400px;
            box-shadow: -5px -5px 20px #fff, 5px 5px 20px #babecc;
        }
        .card:hover{
            transform: scale(1.05);
        }
        .card-img-top{
            width: 362px;
            height: 200px;
        }
        .containerCard{
            width: 362px;
            height: 600px;
            margin: 10px;
        }

        @media only screen and (max-width: 600px) {
            .card-deck{
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-content: center;
                margin-top: 50px;
            }
        }
    </style>
    <div class="globalContainer">
        <div class="top">
            <h1 class="text-muted">Bienvenue sur l'app de gestion d'évènements entre étudiants de l'ENI</h1>
            <h1 class="text-muted">Participe ou organise un évènement !</h1>
            <div>
                <a class="btn btn-info text-light" href="{{ path('app_login') }}" role="button">Connecte toi!</a>
            </div>
        </div>


        {#    {{ dump() }}#}

        <div class="card-deck">

            <div class="containerCard">
                <div class="card">
                    <img class="card-img-top" src="{{ asset("images/welcomePage/afterwork.jpg") }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">After-Work</h5>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus, consequuntur, error. Commodi debitis doloribus eos!</p>
                        <p class="card-text"><small class="text-muted">Connecte toi pour retrouver tous les évènements</small></p>
                    </div>
                </div>
            </div>

            <div class="containerCard">
                <div class="card">
                    <img class="card-img-top" src="images/welcomePage/activities.jpg" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Activitée sportive</h5>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi dicta explicabo hic obcaecati, officia perferendis.</p>
                        <p class="card-text"><small class="text-muted">Connecte toi pour retrouver tous les évènements</small></p>
                    </div>
                </div>
            </div>


            <div class="containerCard">
                <div class="card">
                    <img class="card-img-top" src="images/welcomePage/concert.jpg" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Concert</h5>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto eius libero nesciunt reprehenderit sed tempora.</p>
                        <p class="card-text"><small class="text-muted">Connecte toi pour retrouver tous les évènements</small></p>
                    </div>
                </div>
            </div>

        </div>
    </div>